// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit.
import type React from 'react';

export type ShotEntry = {
  Comp: React.ComponentType;
  config: { id: string; durationInSeconds: number; fps: number; width: number; height: number };
};

export const shots: ShotEntry[] = [];
